# Generated by Django 5.0 on 2023-12-12 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='name',
            new_name='name1',
        ),
    ]
