# Generated by Django 5.0 on 2023-12-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_name_customuser_name1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name1',
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
